# Generated by Django 3.2.4 on 2021-06-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
